### ISSUE TITLE
Heroku Set / Unset Config Per Env Clusters

### ISSUE THREAD

**Issue by HoyaBoya** [blueapron/dual_burner#5]
Feature request by the BA.com team to have a utility to allow for heroku configs to be set / unset easily.

/cc @dylandrop @sclm @travisofthenorth @alexQueue

**Comment by HoyaBoya** [comment]
This has been addressed with follow up commits in #1. There's a still a bit more I can do (tests, cleanup, etc), but this should accomplish what we desired per our chat this morning.

<img width="990" alt="screen shot 2016-02-25 at 2 00 22 pm" src="https://cloud.githubusercontent.com/assets/134368/13330859/cfaf27be-dbc8-11e5-9c81-b266938a2655.png">

**Comment by HoyaBoya** [comment]
I'll resolve this issue when #1 is accepted into master.

**Comment by travisofthenorth** [comment]
:+1: nice

**Comment by HoyaBoya** [comment]
Resolved with `0.1.0`.
